INSERT INTO master_config."ROLE_TYPE" ("ID", "ROLE_TYPE_DESC") VALUES(0, 'Sys_Roles');
INSERT INTO master_config."ROLE_TYPE" ("ID", "ROLE_TYPE_DESC") VALUES(1, 'Client Admin');
INSERT INTO master_config."ROLE_TYPE" ("ID", "ROLE_TYPE_DESC") VALUES(2, 'Client_Roles');

INSERT INTO master_config."STATUS_MASTER" ("ID", "STATUS") VALUES(1, 'Not Started');
INSERT INTO master_config."STATUS_MASTER" ("ID", "STATUS") VALUES(2, 'InProgress');
INSERT INTO master_config."STATUS_MASTER" ("ID", "STATUS") VALUES(3, 'Completed');

INSERT INTO master_config."CLIENT_ROLE_MASTER" ("CLI_ROLE_ID", "ROLE_NAME", "ROLE_TYPE_ID", "DESCRIPTION", "COMMENTS", "CREATED_BY", "is_ACTIVE", "CREATED_DATE_TIME") VALUES(1, 'Client Admin', 1, NULL, NULL, 0, true, CURRENT_TIMESTAMP);
INSERT INTO master_config."CLIENT_ROLE_MASTER" ("CLI_ROLE_ID", "ROLE_NAME", "ROLE_TYPE_ID", "DESCRIPTION", "COMMENTS", "CREATED_BY", "is_ACTIVE", "CREATED_DATE_TIME") VALUES(2, 'Steering committee', 2, NULL, NULL, 0, true, CURRENT_TIMESTAMP);
INSERT INTO master_config."CLIENT_ROLE_MASTER" ("CLI_ROLE_ID", "ROLE_NAME", "ROLE_TYPE_ID", "DESCRIPTION", "COMMENTS", "CREATED_BY", "is_ACTIVE", "CREATED_DATE_TIME") VALUES(3, 'CISO', 2, NULL, NULL, 0, true, CURRENT_TIMESTAMP);
INSERT INTO master_config."CLIENT_ROLE_MASTER" ("CLI_ROLE_ID", "ROLE_NAME", "ROLE_TYPE_ID", "DESCRIPTION", "COMMENTS", "CREATED_BY", "is_ACTIVE", "CREATED_DATE_TIME") VALUES(4, 'Senior Manager', 2, NULL, NULL, 0, true, CURRENT_TIMESTAMP);
INSERT INTO master_config."CLIENT_ROLE_MASTER" ("CLI_ROLE_ID", "ROLE_NAME", "ROLE_TYPE_ID", "DESCRIPTION", "COMMENTS", "CREATED_BY", "is_ACTIVE", "CREATED_DATE_TIME") VALUES(5, 'Manager', 2, NULL, NULL, 0, true, CURRENT_TIMESTAMP);
INSERT INTO master_config."CLIENT_ROLE_MASTER" ("CLI_ROLE_ID", "ROLE_NAME", "ROLE_TYPE_ID", "DESCRIPTION", "COMMENTS", "CREATED_BY", "is_ACTIVE", "CREATED_DATE_TIME") VALUES(6, 'Trainee', 2, NULL, NULL, 0, true, CURRENT_TIMESTAMP);
INSERT INTO master_config."CLIENT_ROLE_MASTER" ("CLI_ROLE_ID", "ROLE_NAME", "ROLE_TYPE_ID", "DESCRIPTION", "COMMENTS", "CREATED_BY", "is_ACTIVE", "CREATED_DATE_TIME") VALUES(7, 'Auditor', 2, NULL, NULL, 0, true, CURRENT_TIMESTAMP);