name: Deploy to Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'

    - name: Build the project
      run: dotnet build

    - name: Build Docker image
      run: docker build -t dotnetdemo .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: docker push dotnetdemo

    - name: Deploy to local server
      run: |
        # Assuming you have Docker installed on your local server
        docker pull dotnetdemo
        docker stop your-container-name || true
        docker rm your-container-name || true
        docker run -d -p 8080:8080 --name demo dotnetdemo

    - name: Push Docker image to Docker Desktop
      run: |
        # Assuming you have Docker Desktop installed
        docker pull dotnetdemo
        docker stop your-container-name || true
        docker rm your-container-name || true
        docker run -d -p 8080:8080 --name demo dotnetdemo

    - name: Push Docker container to GitHub Container Registry
      run: |
        docker pull your-image-name
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker tag your-image-name ghcr.io/your-username/your-image-name:latest
        docker push ghcr.io/techoptima/dotnetdemo:latest
