name: Docker Hub Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push to Docker Hub
run: |
    echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

        docker push techoptima/GRCbackend_Docker
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker pull techoptima/GRCbackend_Docker:latest

      - name: Stop existing container
        run: docker stop your-container-name || true

      - name: Remove existing container
        run: docker rm your-container-name || true

      - name: Run new container
        run: docker run -d --name Docker -p 8080:8080 techoptima/GRCbackend_Docker:latest
