name: Dotnet CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t techoptima/dotnetdocker:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push techoptima/dotnetdocker:latest

  deploy:
    needs: build-and-push
    name: Deploy Dotnet Application to Docker Container
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull techoptima/dotnetdocker:latest

      - name: Stop and remove existing Dotnet application container
        run: |
          docker stop dotnet-app-container || true
          docker rm dotnet-app-container || true

      - name: Run Dotnet application Docker container
        run: docker run -d --name dotnet-app-container -p 8080:8080 techoptima/dotnetdocker:latest
